# Generated by Django 6.1.1 on 2026-09-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="Forces the user to create a new password on their next login. Set automatically when an administrator resets this user's password.", verbose_name='Must Change Password'),
        ),
    ]
