# Generated by Django 6.1.1 on 2026-09-13 08:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Square image recommended. JPG, JPEG, PNG or WEBP. Max 5 MB.', null=True, upload_to=accounts.models.user_avatar_path, verbose_name='Profile Picture'),
        ),
    ]
