# Generated by Django 6.1.1 on 2026-09-17 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('businesses', '0005_extend_operating_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_label', models.CharField(choices=[('OWNER', 'Owner'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('INVENTORY_CLERK', 'Inventory Clerk')], default='CASHIER', max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed'), ('INVITED', 'Invited')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('pwa_access', models.BooleanField(default=False, help_text="Allows this user to access this business via the PWA. The user's CloudProfile.pwa_access_enabled must also be True.", verbose_name='PWA Access')),
                ('branch_access_all', models.BooleanField(default=True, help_text='True → access all branches of this business. False → limited to UserBranchAccess records.', verbose_name='All Branch Access')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_memberships', to='businesses.business', verbose_name='Business')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Business Membership',
                'verbose_name_plural': 'Business Memberships',
                'db_table': 'cloud_business_membership',
            },
        ),
        migrations.CreateModel(
            name='CloudAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_SUSPENDED', 'Member Suspended'), ('MEMBER_REACTIVATED', 'Member Reactivated'), ('ROLE_CHANGED', 'Role Changed'), ('PWA_ENABLED', 'PWA Access Enabled'), ('PWA_DISABLED', 'PWA Access Disabled'), ('BRANCH_ACCESS_GRANTED', 'Branch Access Granted'), ('BRANCH_ACCESS_REVOKED', 'Branch Access Revoked'), ('BRANCH_ACCESS_ALL_SET', 'All-Branch Access Set'), ('DEVICE_REGISTERED', 'Device Registered'), ('DEVICE_SUSPENDED', 'Device Suspended'), ('DEVICE_REVOKED', 'Device Revoked'), ('DEVICE_REACTIVATED', 'Device Reactivated'), ('BUSINESS_CLOUD_ACTIVATED', 'Business Cloud Activated'), ('BUSINESS_CLOUD_SUSPENDED', 'Business Cloud Suspended'), ('BUSINESS_CLOUD_CLOSED', 'Business Cloud Closed'), ('USER_CLOUD_ENABLED', 'User Cloud Account Enabled'), ('USER_CLOUD_SUSPENDED', 'User Cloud Account Suspended')], db_index=True, max_length=40, verbose_name='Action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Safe supplementary data (role names, branch names, device IDs, etc.). Never store passwords, tokens, or activation codes here.', verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_audit_logs', to='businesses.business', verbose_name='Business')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Target User')),
            ],
            options={
                'verbose_name': 'Cloud Audit Log',
                'verbose_name_plural': 'Cloud Audit Logs',
                'db_table': 'cloud_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudBusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cloud_uid', models.UUIDField(editable=False, help_text='Stable cloud identifier — same value as Business.id.', unique=True, verbose_name='Cloud UID')),
                ('cloud_status', models.CharField(choices=[('PENDING', 'Pending Setup'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='PENDING', max_length=20, verbose_name='Cloud Status')),
                ('cloud_registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Cloud Registered At')),
                ('pwa_modules', models.JSONField(blank=True, default=dict, help_text="Dict of module keys → bool.  Controls which PWA modules are available for this business's subscription tier.", verbose_name='PWA Modules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_profile', to='businesses.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Cloud Business Profile',
                'verbose_name_plural': 'Cloud Business Profiles',
                'db_table': 'cloud_business_profile',
            },
        ),
        migrations.CreateModel(
            name='CloudDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_uuid', models.UUIDField(default=uuid.uuid4, help_text='Stable UUID identifying this device across sessions.', unique=True, verbose_name='Device UUID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Device Name')),
                ('device_type', models.CharField(choices=[('POS_TERMINAL', 'POS Terminal'), ('MOBILE', 'Mobile Device'), ('WEB', 'Web / PWA Browser'), ('DESKTOP_APP', 'Desktop App'), ('OTHER', 'Other')], default='POS_TERMINAL', max_length=20, verbose_name='Device Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('token_hash', models.CharField(blank=True, help_text='SHA-256 hash of the device token. Raw token is never stored.', max_length=64, verbose_name='Token Hash')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='App Version')),
                ('os_info', models.CharField(blank=True, help_text='e.g. Windows 11, Android 14, iOS 17 — customer-supplied, not verified.', max_length=150, verbose_name='OS Info')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('first_registered', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_devices', to='businesses.business', verbose_name='Business')),
                ('membership', models.ForeignKey(blank=True, help_text='The business membership that registered this device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_devices', to='cloud.businessmembership', verbose_name='Membership')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revoked By')),
            ],
            options={
                'verbose_name': 'Cloud Device',
                'verbose_name_plural': 'Cloud Devices',
                'db_table': 'cloud_device',
            },
        ),
        migrations.CreateModel(
            name='CloudProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pwa_access_enabled', models.BooleanField(default=False, help_text='Global gate for PWA access. Must also have an active BusinessMembership with pwa_access=True.', verbose_name='PWA Access Enabled')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Phone Verified')),
                ('last_cloud_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last Cloud Activity')),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending Verification')], default='ACTIVE', max_length=20, verbose_name='Cloud Account Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cloud Profile',
                'verbose_name_plural': 'Cloud Profiles',
                'db_table': 'cloud_profile',
            },
        ),
        migrations.CreateModel(
            name='UserBranchAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_access_grants', to='branches.branch', verbose_name='Branch')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accesses', to='cloud.businessmembership', verbose_name='Membership')),
            ],
            options={
                'verbose_name': 'User Branch Access',
                'verbose_name_plural': 'User Branch Accesses',
                'db_table': 'cloud_user_branch_access',
            },
        ),
        migrations.AddIndex(
            model_name='businessmembership',
            index=models.Index(fields=['business', 'status'], name='cloud_busin_busines_63740c_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmembership',
            index=models.Index(fields=['user', 'status'], name='cloud_busin_user_id_459757_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmembership',
            unique_together={('user', 'business')},
        ),
        migrations.AddIndex(
            model_name='cloudauditlog',
            index=models.Index(fields=['business', 'created_at'], name='cloud_audit_busines_6e4b83_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='cloud_audit_actor_i_a16f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudauditlog',
            index=models.Index(fields=['action', 'created_at'], name='cloud_audit_action_1bf1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='clouddevice',
            index=models.Index(fields=['business', 'status'], name='cloud_devic_busines_11581a_idx'),
        ),
        migrations.AddIndex(
            model_name='clouddevice',
            index=models.Index(fields=['device_uuid'], name='cloud_devic_device__676c0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbranchaccess',
            unique_together={('membership', 'branch')},
        ),
    ]
