# Generated by Django 6.1.1 on 2026-09-17 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
        ('synchronization', '0003_alter_syncrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouddevice',
            name='sync_device',
            field=models.ForeignKey(blank=True, help_text='Optional link to the corresponding SyncDevice for offline sync. Populated by Stage 6.2C sync registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_devices', to='synchronization.syncdevice', verbose_name='Sync Device'),
        ),
        migrations.AlterField(
            model_name='cloudauditlog',
            name='action',
            field=models.CharField(choices=[('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_SUSPENDED', 'Member Suspended'), ('MEMBER_REACTIVATED', 'Member Reactivated'), ('ROLE_CHANGED', 'Role Changed'), ('PWA_ENABLED', 'PWA Access Enabled'), ('PWA_DISABLED', 'PWA Access Disabled'), ('BRANCH_ACCESS_GRANTED', 'Branch Access Granted'), ('BRANCH_ACCESS_REVOKED', 'Branch Access Revoked'), ('BRANCH_ACCESS_ALL_SET', 'All-Branch Access Set'), ('DEVICE_REGISTERED', 'Device Registered'), ('DEVICE_SUSPENDED', 'Device Suspended'), ('DEVICE_REVOKED', 'Device Revoked'), ('DEVICE_REACTIVATED', 'Device Reactivated'), ('DEVICE_AUTH_FAILED', 'Device Auth Failed'), ('DEVICE_HEARTBEAT', 'Device Heartbeat'), ('BUSINESS_CLOUD_ACTIVATED', 'Business Cloud Activated'), ('BUSINESS_CLOUD_SUSPENDED', 'Business Cloud Suspended'), ('BUSINESS_CLOUD_CLOSED', 'Business Cloud Closed'), ('LICENSE_VERIFIED_OK', 'License Verified OK'), ('LICENSE_VERIFIED_FAIL', 'License Verification Failed'), ('CLOUD_ACCESS_DENIED', 'Cloud Access Denied'), ('USER_CLOUD_ENABLED', 'User Cloud Account Enabled'), ('USER_CLOUD_SUSPENDED', 'User Cloud Account Suspended')], db_index=True, max_length=40, verbose_name='Action'),
        ),
    ]
