# Generated by Django 6.1.1 on 2026-09-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_add_sync_device_bridge_and_audit_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudauditlog',
            name='action',
            field=models.CharField(choices=[('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_SUSPENDED', 'Member Suspended'), ('MEMBER_REACTIVATED', 'Member Reactivated'), ('ROLE_CHANGED', 'Role Changed'), ('PWA_ENABLED', 'PWA Access Enabled'), ('PWA_DISABLED', 'PWA Access Disabled'), ('BRANCH_ACCESS_GRANTED', 'Branch Access Granted'), ('BRANCH_ACCESS_REVOKED', 'Branch Access Revoked'), ('BRANCH_ACCESS_ALL_SET', 'All-Branch Access Set'), ('DEVICE_REGISTERED', 'Device Registered'), ('DEVICE_SUSPENDED', 'Device Suspended'), ('DEVICE_REVOKED', 'Device Revoked'), ('DEVICE_REACTIVATED', 'Device Reactivated'), ('DEVICE_AUTH_FAILED', 'Device Auth Failed'), ('DEVICE_HEARTBEAT', 'Device Heartbeat'), ('BUSINESS_CLOUD_ACTIVATED', 'Business Cloud Activated'), ('BUSINESS_CLOUD_SUSPENDED', 'Business Cloud Suspended'), ('BUSINESS_CLOUD_CLOSED', 'Business Cloud Closed'), ('LICENSE_VERIFIED_OK', 'License Verified OK'), ('LICENSE_VERIFIED_FAIL', 'License Verification Failed'), ('CLOUD_ACCESS_DENIED', 'Cloud Access Denied'), ('USER_CLOUD_ENABLED', 'User Cloud Account Enabled'), ('USER_CLOUD_SUSPENDED', 'User Cloud Account Suspended'), ('SYNC_UPLOAD_OK', 'Sync Upload Accepted'), ('SYNC_UPLOAD_FAIL', 'Sync Upload Failed'), ('SYNC_DOWNLOAD', 'Sync Download'), ('SYNC_CONFLICT', 'Sync Conflict Detected'), ('SYNC_RECOVERY', 'Sync Recovery: SYNCING→PENDING')], db_index=True, max_length=40, verbose_name='Action'),
        ),
    ]
