# Generated by Django 5.2.17 on 2026-09-18 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_add_sync_audit_actions'),
        ('licensing', '0003_add_trial_code_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(help_text='SHA-256 of the raw one-time reservation token.', max_length=64, unique=True, verbose_name='Token Hash')),
                ('status', models.CharField(choices=[('PENDING', 'Pending — awaiting completion'), ('COMPLETED', 'Completed — TrialCode consumed'), ('EXPIRED', 'Expired — timed out before completion'), ('CANCELLED', 'Cancelled — abandoned')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Reservation is invalid after this timestamp.', verbose_name='Expires At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_code', models.ForeignKey(help_text='The TrialCode voucher that this reservation holds.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='licensing.trialcode', verbose_name='Trial Code')),
            ],
            options={
                'verbose_name': 'Activation Reservation',
                'verbose_name_plural': 'Activation Reservations',
                'db_table': 'cloud_activation_reservation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='cloud_activ_status_fbf527_idx')],
            },
        ),
    ]
