# Generated by Django 5.0.14 on 2026-09-04 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('supermarket', 'Supermarket'), ('pharmacy', 'Pharmacy'), ('phone_shop', 'Phone Shop'), ('electronics', 'Electronics'), ('boutique', 'Boutique'), ('cosmetics', 'Cosmetics'), ('restaurant', 'Restaurant'), ('wholesale', 'Wholesale'), ('general', 'General')], default='general', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='Taxpayer Identification Number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('currency_symbol', models.CharField(default='GH₵', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses_business',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_config', models.JSONField(blank=True, default=dict)),
                ('receipt_config', models.JSONField(blank=True, default=dict)),
                ('inventory_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
                'db_table': 'businesses_settings',
            },
        ),
    ]
