# Generated by Django 6.1.1 on 2026-09-12 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The primary account that owns and manages this business.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL, verbose_name='Business Owner'),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Subscription Tier'),
        ),
    ]
