# Generated by Django 6.1.1 on 2026-09-14 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_add_owner_and_subscription_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_category',
            field=models.CharField(choices=[('PROVISION_GROCERY', 'Provision / Grocery'), ('SUPERMARKET', 'Supermarket'), ('GENERAL_RETAIL', 'General Retail'), ('COSMETICS', 'Cosmetics'), ('PHARMACY', 'Pharmacy'), ('ELECTRONICS', 'Electronics'), ('PHONE_ACCESSORIES', 'Phone & Accessories'), ('FASHION_CLOTHING', 'Fashion / Clothing'), ('SHOES', 'Shoes'), ('SERVICE', 'Service'), ('OTHER', 'Other')], default='GENERAL_RETAIL', help_text='The type of business — controls default pricing behaviour.', max_length=30, verbose_name='Business Category'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='allow_cashier_price_negotiation',
            field=models.BooleanField(default=False, help_text='When True, Cashiers can finalise a negotiated (customer-agreed) price at the POS without manager approval. Admins and Managers can always negotiate regardless of this setting.', verbose_name='Allow Cashier Price Negotiation'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL, verbose_name='Business Owner'),
        ),
    ]
