# Generated by Django 6.1.1 on 2026-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_add_business_category_and_pricing_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='inventory_mode',
            field=models.CharField(choices=[('STOCK_ENABLED', 'Stock Enabled'), ('SALES_ONLY', 'Sales Only (No Stock Tracking)')], default='STOCK_ENABLED', help_text='STOCK_ENABLED: purchases increase stock, sales decrease stock, low-stock alerts fire, movements are recorded. SALES_ONLY: products can be sold without requiring stock quantities; no stock movements are created and stock controls are hidden.', max_length=20, verbose_name='Inventory Mode'),
        ),
    ]
