# Generated by Django 6.1.1 on 2026-09-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_add_inventory_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='inventory_mode',
            field=models.CharField(choices=[('FULL_POS', 'Full POS + Inventory'), ('INVENTORY_ONLY', 'Inventory / Stock Only'), ('POS_ONLY', 'POS Only'), ('STOCK_ENABLED', 'Stock Enabled (legacy)'), ('SALES_ONLY', 'Sales Only (legacy)')], default='FULL_POS', help_text='FULL_POS: full POS checkout + inventory management. INVENTORY_ONLY: stock/inventory management only — new sales are blocked. POS_ONLY: sales/checkout only — inventory workflows are hidden. Legacy values STOCK_ENABLED and SALES_ONLY are mapped to FULL_POS and POS_ONLY.', max_length=20, verbose_name='Operating Mode'),
        ),
    ]
