# Generated by Django 5.2.17 on 2026-09-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_extend_operating_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='branch_mode',
            field=models.CharField(choices=[('SINGLE', 'Single Branch'), ('MULTI', 'Multiple Branches')], default='SINGLE', help_text='SINGLE: business has one fixed location — branch management is hidden. MULTI: business has multiple locations — branch management is enabled.', max_length=10, verbose_name='Branch Mode'),
        ),
    ]
