# Generated by Django 5.0.14 on 2026-09-04 04:42

import django.db.models.deletion
import phones.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('model_code', models.CharField(max_length=50)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('processor', models.CharField(blank=True, max_length=255)),
                ('ram_gb', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('storage_gb', models.IntegerField(default=0)),
                ('battery_mah', models.IntegerField(default=0)),
                ('screen_size_inch', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('display_type', models.CharField(blank=True, max_length=100)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('camera_spec', models.JSONField(blank=True, default=dict)),
                ('connectivity', models.JSONField(blank=True, default=dict)),
                ('sim_type', models.CharField(choices=[('SINGLE_SIM', 'Single SIM'), ('DUAL_SIM', 'Dual SIM'), ('ESIM', 'eSIM')], default='DUAL_SIM', max_length=20)),
                ('has_5g', models.BooleanField(default=False)),
                ('body_dimensions', models.CharField(blank=True, max_length=100)),
                ('weight_g', models.IntegerField(blank=True, null=True)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phone Model',
                'verbose_name_plural': 'Phone Models',
                'db_table': 'phones_phone_model',
                'ordering': ['brand__name', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('storage_gb', models.IntegerField(default=0)),
                ('ram_gb', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('sku_suffix', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phone Variant',
                'verbose_name_plural': 'Phone Variants',
                'db_table': 'phones_phone_variant',
            },
        ),
        migrations.CreateModel(
            name='PhoneWarranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warranty_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('warranty_type', models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('EXTENDED', 'Extended'), ('STORE', 'Store')], default='MANUFACTURER', max_length=20)),
                ('terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('VOIDED', 'Voided'), ('CLAIMED', 'Claimed')], default='ACTIVE', max_length=20)),
                ('claim_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phone Warranty',
                'verbose_name_plural': 'Phone Warranties',
                'db_table': 'phones_phone_warranty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='phone_brands/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_brands', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Phone Brand',
                'verbose_name_plural': 'Phone Brands',
                'db_table': 'phones_phone_brand',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_from', models.CharField(blank=True, max_length=20)),
                ('status_to', models.CharField(blank=True, max_length=20)),
                ('event_type', models.CharField(choices=[('PURCHASED', 'Purchased'), ('RECEIVED_STOCK', 'Received Stock'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('REPAIRED', 'Repaired'), ('LOST', 'Lost'), ('FOUND', 'Found'), ('STOLEN', 'Stolen'), ('RECOVERED', 'Recovered'), ('WRITTEN_OFF', 'Written Off')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_history', to='businesses.business')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone History',
                'verbose_name_plural': 'Phone Histories',
                'db_table': 'phones_phone_history',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='PhoneIMEI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imei_1', models.CharField(max_length=15, unique=True, validators=[phones.models.validate_luhn_checksum])),
                ('imei_2', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[phones.models.validate_luhn_checksum])),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('sim_lock_status', models.CharField(choices=[('UNLOCKED', 'Unlocked'), ('CARRIER_LOCKED', 'Carrier Locked'), ('ICLOUD_LOCKED', 'iCloud Locked'), ('BLACKLISTED', 'Blacklisted'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('grade_condition', models.CharField(choices=[('NEW', 'New'), ('OPEN_BOX', 'Open Box'), ('A_GRADE', 'A Grade'), ('B_GRADE', 'B Grade'), ('C_GRADE', 'C Grade'), ('DAMAGED', 'Damaged'), ('REFURBISHED', 'Refurbished')], default='NEW', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('warranty_months', models.IntegerField(default=12)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INSTOCK', 'In Stock'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('REPAIR_IN', 'Repair In'), ('REPAIR_OUT', 'Repair Out'), ('LOST', 'Lost'), ('STOLEN', 'Stolen'), ('WRITE_OFF', 'Write Off')], default='INSTOCK', max_length=20)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
                ('physical_condition_notes', models.TextField(blank=True)),
                ('accessories', models.JSONField(blank=True, default=list)),
                ('box_included', models.BooleanField(default=False)),
                ('charger_included', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_imeis', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_imeis', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_phone_imeis', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_imeis', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Phone IMEI',
                'verbose_name_plural': 'Phone IMEIs',
                'db_table': 'phones_phone_imei',
                'ordering': ['-created_at'],
            },
        ),
    ]
