# Generated by Django 5.0.14 on 2026-09-04 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('businesses', '0001_initial'),
        ('customers', '0002_initial'),
        ('phones', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneimei',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_imeis', to='products.product'),
        ),
        migrations.AddField(
            model_name='phoneimei',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_imeis', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='phoneimei',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_imeis', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='phoneimei',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_imeis', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='phoneimei',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_imeis', to='branches.warehouse'),
        ),
        migrations.AddField(
            model_name='phonehistory',
            name='imei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='phones.phoneimei'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='phones.phonebrand'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_models', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_model', to='products.product'),
        ),
        migrations.AddField(
            model_name='phoneimei',
            name='phone_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imeis', to='phones.phonemodel'),
        ),
        migrations.AddField(
            model_name='phonevariant',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_variants', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='phonevariant',
            name='phone_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='phones.phonemodel'),
        ),
        migrations.AddField(
            model_name='phonevariant',
            name='product_variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_variant', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='phoneimei',
            name='phone_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imeis', to='phones.phonevariant'),
        ),
        migrations.AddField(
            model_name='phonewarranty',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_warranties', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='phonewarranty',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_warranties', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='phonewarranty',
            name='imei',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='phones.phoneimei'),
        ),
        migrations.AddField(
            model_name='phonewarranty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_warranties', to='products.product'),
        ),
        migrations.AddField(
            model_name='phonewarranty',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_warranties', to='sales.sale'),
        ),
        migrations.AlterUniqueTogether(
            name='phonebrand',
            unique_together={('business', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='phonemodel',
            unique_together={('business', 'model_code')},
        ),
    ]
