# Generated by Django 5.0.14 on 2026-09-04 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('businesses', '0001_initial'),
        ('customers', '0002_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='brand',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_barcodes', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='bundle_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='products.product'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bundles', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='component_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_memberships', to='products.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='products.product'),
        ),
        migrations.AddField(
            model_name='productpricelist',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_lists', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='productpricelist',
            name='customer_tiers',
            field=models.ManyToManyField(blank=True, related_name='price_lists', to='customers.loyaltytier'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.productpricelist'),
        ),
        migrations.AddField(
            model_name='productstocklevel',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_levels', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='productstocklevel',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_levels', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='productstocklevel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='products.product'),
        ),
        migrations.AddField(
            model_name='productstocklevel',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_levels', to='branches.warehouse'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AddField(
            model_name='productstocklevel',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='batch',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rates',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.taxrate'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='converted_units', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_measures', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_products', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_products', to='products.unitofmeasure'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('business', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('business', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='productpricelist',
            unique_together={('business', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='productstocklevel',
            unique_together={('product', 'variant', 'branch', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('business', 'product', 'batch_number')},
        ),
        migrations.AlterUniqueTogether(
            name='taxrate',
            unique_together={('business', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='unitofmeasure',
            unique_together={('business', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'sku')},
        ),
    ]
