# Generated by Django 6.1.1 on 2026-09-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Price'), ('NEGOTIABLE', 'Negotiable Price')], default='FIXED', help_text='FIXED: the selling price is used as-is. NEGOTIABLE: authorised staff may agree a different price with the customer at checkout.', max_length=20, verbose_name='Pricing Type'),
        ),
    ]
