# Generated by Django 6.1.1 on 2026-09-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_pricing_type_to_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date the purchase order was placed', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='qty_purchased',
            field=models.IntegerField(default=0, help_text='Total quantity on the purchase order for this batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='qty_received',
            field=models.IntegerField(default=0, help_text='Quantity actually received into stock'),
        ),
        migrations.AddField(
            model_name='batch',
            name='qty_remaining',
            field=models.IntegerField(default=0, help_text='Units still in stock from this batch (decremented on each sale)'),
        ),
        migrations.AddField(
            model_name='batch',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date goods were physically received', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='stock_out_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when qty_remaining first reached zero for this batch', null=True),
        ),
    ]
