# Generated by Django 6.1.1 on 2026-09-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_batch_tracking_fields'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='The PO that created this batch (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='purchases.purchaseorder'),
        ),
    ]
