# Generated by Django 6.1.1 on 2026-09-13 00:52

import django.db.models.deletion
import licensing.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_add_owner_and_subscription_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('LIFETIME', 'Lifetime')], default='SUBSCRIPTION', max_length=20, verbose_name='License Type')),
                ('activation_code', models.CharField(default=licensing.models._generate_code, help_text='Share this code with the customer to activate or renew their license.', max_length=30, unique=True, verbose_name='Activation Code')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank for Lifetime licenses.', null=True, verbose_name='Expiry Date')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='businesses.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'licensing_license',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseRenewalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(default='RENEWAL', max_length=20)),
                ('code_used', models.CharField(max_length=30)),
                ('previous_expiry', models.DateField(blank=True, null=True)),
                ('new_expiry', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_logs', to='licensing.license')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'licensing_renewal_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
