# Generated by Django 6.1.1 on 2026-09-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('LIFETIME', 'Lifetime'), ('TRIAL', '7-Day Trial')], default='SUBSCRIPTION', max_length=20, verbose_name='License Type'),
        ),
    ]
