# Generated by Django 6.1.1 on 2026-09-18 02:36

import django.db.models.deletion
import licensing.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_add_trial_license_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=licensing.models._generate_code, help_text='Share this code with the customer to activate their 7-day trial.', max_length=30, unique=True, verbose_name='Trial Code')),
                ('status', models.CharField(choices=[('PENDING', 'Pending — not yet activated'), ('USED', 'Used — activated by a customer'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Internal reference, e.g. customer name or order ID.', verbose_name='Notes')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_license', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_code', to='licensing.license', verbose_name='Activated License')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Trial Code',
                'verbose_name_plural': 'Trial Codes',
                'db_table': 'licensing_trial_code',
                'ordering': ['-created_at'],
            },
        ),
    ]
