# Generated by Django 6.1.1 on 2026-09-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrecord',
            name='branch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='syncrecord',
            name='business_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='syncrecord',
            name='device_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='syncrecord',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='syncrecord',
            index=models.Index(fields=['device_id', 'created_at'], name='synchroniza_device__d10ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrecord',
            index=models.Index(fields=['business_id', 'branch_id', 'created_at'], name='synchroniza_busines_d5e5f7_idx'),
        ),
    ]
