# Generated by Django 6.1.1 on 2026-09-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0002_syncrecord_branch_id_syncrecord_business_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed'), ('conflict', 'Conflict')], db_index=True, default='pending', max_length=20),
        ),
    ]
