# Generated by Django 6.1.1 on 2026-09-17 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0003_alter_syncrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncdevice',
            name='sync_checkpoint',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the last successfully downloaded batch. Used as the 'since' cursor for the next download request. Never advanced until the downloaded records are safely applied.", null=True),
        ),
        migrations.CreateModel(
            name='SyncConflictLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True)),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=150)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('branch_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('client_version', models.PositiveIntegerField(default=1)),
                ('client_payload', models.JSONField(blank=True, default=dict)),
                ('server_version', models.PositiveIntegerField(default=1)),
                ('server_payload', models.JSONField(blank=True, default=dict)),
                ('resolution', models.CharField(choices=[('server_wins', 'Server version accepted'), ('client_wins', 'Client version accepted'), ('manual', 'Manually resolved'), ('deferred', 'Deferred — awaiting manual review')], db_index=True, default='deferred', max_length=20)),
                ('sync_record_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Sync Conflict Log',
                'verbose_name_plural': 'Sync Conflict Logs',
                'db_table': 'synchronization_sync_conflict_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record_id', 'app_label', 'model_name'], name='synchroniza_record__2e4806_idx'), models.Index(fields=['business_id', 'created_at'], name='synchroniza_busines_153704_idx')],
            },
        ),
    ]
