# Generated by Django 5.0.14 on 2026-09-04 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleonaccount',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_sales', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='saleonaccountpayment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_payments', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='saleonaccountpayment',
            name='credit_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.saleonaccount'),
        ),
        migrations.AddField(
            model_name='saleonaccountpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_payments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='saleonaccountpayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_account_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='customergroup',
            unique_together={('business', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='loyaltytier',
            unique_together={('business', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='saleonaccount',
            unique_together={('business', 'invoice_number')},
        ),
    ]
