# Generated by Django 6.1.1 on 2026-09-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_add_owner_and_subscription_tier'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('business', 'phone')},
        ),
    ]
