# Generated by Django 6.1.1 on 2026-09-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Optional IMEI / serial number for serialised products (phones, electronics, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('LOST', 'Lost / Missing'), ('THEFT', 'Theft'), ('INTERNAL_USE', 'Internal Use'), ('STOCK_CORRECTION', 'Stock Correction'), ('SUPPLIER_RETURN', 'Supplier Return'), ('FOUND', 'Found Stock'), ('WRONG_ENTRY', 'Wrong Entry'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('RETURN_IN', 'Return In'), ('RETURN_OUT', 'Return Out'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('OPENING_STOCK', 'Opening Stock'), ('STOCK_COUNT', 'Stock Count'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALE_RETURN', 'Sale Return'), ('LOST', 'Lost'), ('THEFT', 'Theft'), ('INTERNAL_USE', 'Internal Use'), ('STOCK_CORRECTION', 'Stock Correction'), ('SUPPLIER_RETURN', 'Supplier Return'), ('FOUND_STOCK', 'Found Stock')], max_length=30),
        ),
    ]
