# Generated by Django 6.1.1 on 2026-09-14 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_expand_adjustment_reasons_and_serial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='discrepancy_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='discrepancy_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='discrepancy_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='discrepancy_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_discrepancy_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='has_discrepancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_released', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_method',
            field=models.CharField(choices=[('PHYSICAL_COLLECTION', 'Physical Collection'), ('DELIVERY', 'Delivery / Dispatch'), ('OTHER', 'Other')], default='DELIVERY', max_length=25),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='condition',
            field=models.CharField(blank=True, help_text='Product condition e.g. New, Refurbished, Used', max_length=30),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='IMEI / serial number for phones or electronics', max_length=100),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DRAFT', 'Draft'), ('SENT', 'Sent')], default='REQUESTED', max_length=20),
        ),
    ]
