# Generated by Django 6.1.1 on 2026-09-14 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='negotiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiated_sale_items', to=settings.AUTH_USER_MODEL, verbose_name='Negotiated By'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='negotiated_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer-agreed price per unit. Product base price is unchanged.', max_digits=15, null=True, verbose_name='Negotiated Unit Price'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='original_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product selling_price at time of sale, preserved for audit.', max_digits=15, null=True, verbose_name='Original Price Snapshot'),
        ),
    ]
