# Generated by Django 6.1.1 on 2026-10-07 21:20

import backups.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        ('businesses', '0006_add_branch_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_file', models.FileField(upload_to=backups.models.cloud_backup_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_backups', to='businesses.business')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud Backup',
                'verbose_name_plural': 'Cloud Backups',
                'db_table': 'backups_cloud_backup',
                'ordering': ['-created_at'],
            },
        ),
    ]
