# Generated by Django 5.0.14 on 2026-09-04 04:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('emergency_contact', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_branches', models.ManyToManyField(blank=True, related_name='allowed_employees', to='branches.branch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='businesses.business')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees_employee',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_number', models.CharField(max_length=50)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('closing_cash_counted', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('closing_cash_expected', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FORCE_CLOSED', 'Force Closed')], default='OPEN', max_length=20)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('closing_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shifts', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shifts', to='businesses.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employees.employee')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shifts', to='branches.register')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': 'employees_shift',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashDrawerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('OPEN', 'Open Drawer'), ('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out'), ('NO_SALE', 'No Sale'), ('PAYIN', 'Pay In'), ('PAYOUT', 'Pay Out')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawer_events', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawer_events', to='businesses.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawer_events', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawer_events', to='employees.shift')),
            ],
            options={
                'verbose_name': 'Cash Drawer Event',
                'verbose_name_plural': 'Cash Drawer Events',
                'db_table': 'employees_cash_drawer_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['business', 'status'], name='employees_e_busines_d93e78_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch', 'status'], name='employees_e_branch__045d1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('business', 'employee_number')},
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['business', 'status'], name='employees_s_busines_2d2aee_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['branch', 'status'], name='employees_s_branch__539ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['employee', 'status'], name='employees_s_employe_a13fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['register', 'status'], name='employees_s_registe_b12ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['open_time', 'close_time'], name='employees_s_open_ti_d484f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('business', 'shift_number')},
        ),
        migrations.AddIndex(
            model_name='cashdrawerevent',
            index=models.Index(fields=['business', 'event_type'], name='employees_c_busines_39e6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrawerevent',
            index=models.Index(fields=['branch', 'event_type'], name='employees_c_branch__f01ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrawerevent',
            index=models.Index(fields=['shift', 'event_type'], name='employees_c_shift_i_fd4b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrawerevent',
            index=models.Index(fields=['created_at'], name='employees_c_created_f1aadb_idx'),
        ),
    ]
