# Generated by Django 5.0.14 on 2026-09-04 04:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('supplier_type', models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('DISTRIBUTOR', 'Distributor'), ('WHOLESALER', 'Wholesaler'), ('IMPORTER', 'Importer'), ('LOCAL', 'Local')], default='LOCAL', max_length=30)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='Taxpayer Identification Number')),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit_days', models.IntegerField(default=0)),
                ('payment_terms', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('bank_swift', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers_supplier',
                'ordering': ['name'],
                'unique_together': {('business', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SupplierBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_balances', to='businesses.business')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Balance',
                'verbose_name_plural': 'Supplier Balances',
                'db_table': 'suppliers_supplier_balance',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Contact',
                'verbose_name_plural': 'Supplier Contacts',
                'db_table': 'suppliers_supplier_contact',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_sku', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('moq', models.IntegerField(default=1, verbose_name='Minimum Order Quantity')),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('is_preferred', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_product_prices', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='suppliers.supplier')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Supplier Product Price',
                'verbose_name_plural': 'Supplier Product Prices',
                'db_table': 'suppliers_supplier_product_price',
                'ordering': ['-is_preferred', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('REFUND', 'Refund')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reference_type', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transaction_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_transactions', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Transaction',
                'verbose_name_plural': 'Supplier Transactions',
                'db_table': 'suppliers_supplier_transaction',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
