# Generated by Django 5.0.14 on 2026-09-04 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VOID', 'Void'), ('REFUND', 'Refund'), ('DISCOUNT', 'Discount'), ('OVERRIDE', 'Override'), ('ADJUSTMENT', 'Adjustment'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('BACKUP', 'Backup'), ('RESTORE', 'Restore'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CANCEL', 'Cancel'), ('CLOSE', 'Close'), ('OPEN', 'Open')], max_length=30)),
                ('module', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict, null=True)),
                ('new_values', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='businesses.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'action'], name='audit_audit_busines_a49845_idx'), models.Index(fields=['business', 'module'], name='audit_audit_busines_d31014_idx'), models.Index(fields=['business', 'entity_type'], name='audit_audit_busines_a6d558_idx'), models.Index(fields=['user', 'action'], name='audit_audit_user_id_f345e1_idx'), models.Index(fields=['created_at'], name='audit_audit_created_a57734_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__c3acd0_idx')],
            },
        ),
    ]
