# Generated by Django 5.0.14 on 2026-09-04 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('DROP', 'Drop'), ('INHALER', 'Inhaler'), ('SUPPOSITORY', 'Suppository'), ('PATCH', 'Patch'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('administration_route', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('OPHTHALMIC', 'Ophthalmic'), ('OTIC', 'Otic'), ('TOPICAL', 'Topical'), ('RECTAL', 'Rectal'), ('VAGINAL', 'Vaginal'), ('INHALATION', 'Inhalation'), ('OTHER', 'Other')], default='ORAL', max_length=20)),
                ('active_ingredients', models.JSONField(blank=True, default=list)),
                ('drug_class', models.CharField(choices=[('ANTIBIOTIC', 'Antibiotic'), ('ANALGESIC', 'Analgesic'), ('ANTI_HYPERTENSIVE', 'Anti-Hypertensive'), ('ANTI_DIABETIC', 'Anti-Diabetic'), ('ANTIHISTAMINE', 'Antihistamine'), ('NSAID', 'NSAID'), ('PPI', 'PPI'), ('STATIN', 'Statin'), ('CORTICOSTEROID', 'Corticosteroid'), ('BRONCHODILATOR', 'Bronchodilator'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('schedule', models.CharField(choices=[('OTC', 'OTC'), ('SCHEDULE_2', 'Schedule 2'), ('SCHEDULE_3', 'Schedule 3'), ('SCHEDULE_4', 'Schedule 4'), ('NARCOTIC', 'Narcotic'), ('CONTROLLED', 'Controlled')], default='OTC', max_length=20)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('pregnancy_category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('X', 'X'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('common_side_effects', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('storage_instructions', models.TextField(blank=True)),
                ('is_pharmacist_only', models.BooleanField(default=False)),
                ('drug_registration_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'pharmacy_medicine',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10)),
                ('patient_phone', models.CharField(blank=True, max_length=20)),
                ('patient_address', models.TextField(blank=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('doctor_phone', models.CharField(blank=True, max_length=20)),
                ('doctor_reg_number', models.CharField(blank=True, max_length=100)),
                ('hospital_clinic', models.CharField(blank=True, max_length=255)),
                ('diagnosis', models.TextField(blank=True)),
                ('prescription_date', models.DateField()),
                ('valid_until_date', models.DateField(blank=True, null=True)),
                ('is_repeat', models.BooleanField(default=False)),
                ('repeat_count', models.IntegerField(default=0)),
                ('max_repeats', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSED', 'Dispensed'), ('PARTIALLY_DISPENSED', 'Partially Dispensed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'pharmacy_prescription',
                'ordering': ['-prescription_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dosage_instruction', models.TextField(blank=True)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('quantity_prescribed', models.IntegerField(default=0)),
                ('quantity_dispensed', models.IntegerField(default=0)),
                ('quantity_remaining', models.IntegerField(default=0)),
                ('refill_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
                'db_table': 'pharmacy_prescription_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DrugAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('ingredient_name', models.CharField(blank=True, max_length=255)),
                ('reaction_type', models.CharField(choices=[('RASH', 'Rash'), ('ITCHING', 'Itching'), ('SWELLING', 'Swelling'), ('ANAPHYLAXIS', 'Anaphylaxis'), ('GI_DISTRESS', 'GI Distress'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('LIFE_THREATENING', 'Life Threatening')], default='MILD', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_allergies', to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_allergies', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Drug Allergy',
                'verbose_name_plural': 'Drug Allergies',
                'db_table': 'pharmacy_drug_allergy',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('SEVERE', 'Severe')], default='MODERATE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('clinical_significance', models.TextField(blank=True)),
                ('management', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_interactions', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Drug Interaction',
                'verbose_name_plural': 'Drug Interactions',
                'db_table': 'pharmacy_drug_interaction',
            },
        ),
        migrations.CreateModel(
            name='DrugStockFEFO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batches_ordered', models.JSONField(blank=True, default=list)),
                ('total_available_qty', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fefo_stocks', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_stock_fefo', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Drug Stock FEFO',
                'verbose_name_plural': 'Drug Stock FEFOs',
                'db_table': 'pharmacy_drug_stock_fefo',
            },
        ),
    ]
