# Generated by Django 5.0.14 on 2026-09-04 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('businesses', '0001_initial'),
        ('pharmacy', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drugstockfefo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fefo_stocks', to='products.product'),
        ),
        migrations.AddField(
            model_name='drugstockfefo',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fefo_stocks', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='drugstockfefo',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fefo_stocks', to='branches.warehouse'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='products.product'),
        ),
        migrations.AddField(
            model_name='drugstockfefo',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fefo_stocks', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='medicine_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_a', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='medicine_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_b', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='drugallergy',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergy_reports', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='products.batch'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='products.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='druginteraction',
            unique_together={('business', 'medicine_a', 'medicine_b')},
        ),
    ]
